### ISSUE TITLE
Feedback function teacher - parent backend

### ISSUE THREAD

**Issue by JacobStokholms** [aau-giraf/foodplanner-api#101]
## Description for feedback chat function jf. figma 20/11.
We need a chat between a parent and a teacher.
The chat should be an open thread with messages that are timestamped and marked if relevant to a specific meal

## Todo
- [x] Add SignalR to backend
- [x] Modify user in backend to allow chat threads
- [x] Create chat threads class which consists of messages
- [x] Create messages class 
   - [x] message add
   - [x] message delete
   - [x] message edit 
- [x] Create DTOs
- [x] Create Repositories
- [x] Create Services
- [x] Create Controllers
- [ ] Create ChatHub class which connects everything and turns the websocket on
